"""Module containing game constants."""

# Weapon constants
WEAPON_ROCK_NAME = "Rock"
WEAPON_ROCK_DAMAGE_BONUS = 2
WEAPON_ROCK_DESCRIPTION = "A simple rock"

WEAPON_PAPER_NAME = "Paper"
WEAPON_PAPER_DAMAGE_BONUS = 3
WEAPON_PAPER_DESCRIPTION = "A magical paper"

WEAPON_SCISSORS_NAME = "Scissors"
WEAPON_SCISSORS_DAMAGE_BONUS = 4
WEAPON_SCISSORS_DESCRIPTION = "Sharp scissors"

WEAPON_DAGGER_NAME = "Dagger"
WEAPON_DAGGER_DAMAGE_BONUS = 5
WEAPON_DAGGER_DESCRIPTION = "A sharp dagger"

WEAPON_STAFF_NAME = "Staff"
WEAPON_STAFF_DAMAGE_BONUS = 3
WEAPON_STAFF_DESCRIPTION = "A magical staff"

# Boss constants
BOSS_WEAPON_NAME = "Boss Weapon"
BOSS_WEAPON_DAMAGE_BONUS = 5
BOSS_WEAPON_DESCRIPTION = "A powerful weapon"

# Character stats
PLAYER_START_HEALTH = 110
PLAYER_START_DAMAGE = 10
PLAYER_START_DEFENSE = 0

# Boss stats
BOSS_START_HEALTH = 90
BOSS_START_DAMAGE = 13
BOSS_START_DEFENSE = 0

# Game settings
DEFAULT_PLAYER_NAME = "Hero"
MAX_HEALTH = 200
MIN_HEALTH = 0
MAX_DAMAGE = 50
MIN_DAMAGE = 0
MAX_DEFENSE = 20
MIN_DEFENSE = 0
